export const paths = {
  home: '/',
  login: '/login',
  register: '/register',
  onboardingProvisioning: '/onboarding/provisioning',
  accountBeingPrepared: '/onboarding/account-preparing',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  careers: '/careers',
  vendorTenders: (token: string | number) => `/vendor-tenders/${token}`,
  vendorTenderSuccess: '/vendor-tenders/success',
  dashboard: '/dashboard',
  dashboards: {
    account: '/account',
    fleet: '/dashboard/fleet',
    depot: '/dashboard/depot',
    inventory: '/dashboard/inventory',
    project: '/dashboard/project',
    distribution: '/dashboard/distribution',
    support: '/dashboard/support-tickets',
    hrm: '/hrm',
  },
  profile: '/profile',
  settings: '/settings',
  users: {
    index: '/users',
    create: '/users/create',
    edit: (id: string | number) => `/users/${id}/edit`,
    provisioning: (id: string | number, companyId: string | number) =>
      `/users/${id}/provisioning?company_id=${companyId}`,
    changePassword: (id: string | number) => `/users/${id}/change-password`,
    loginHistory: '/users/login-history',
  },
  roles: {
    index: '/roles',
    create: '/roles/create',
    edit: (id: string | number) => `/roles/${id}/edit`,
  },
  media: '/media-library',
  emailTemplates: '/email-templates',
  emailTemplateEdit: (id: string | number) => `/email-templates/${id}/edit`,
  notificationTemplates: '/notification-templates',
  notificationTemplateEdit: (id: string | number) => `/notification-templates/${id}/edit`,
  depots: {
    index: '/depots',
    create: '/depots/create',
    show: (id: number | string) => `/depots/${id}`,
    edit: (id: number | string) => `/depots/${id}/edit`,
    depotReps: '/hrm/employees/depot-reps',
    depotRepCreate: '/hrm/employees/depot-reps/create',
    depotRepShow: (id: number | string) => `/hrm/employees/depot-reps/${id}`,
    depotRepEdit: (id: number | string) => `/hrm/employees/depot-reps/${id}/edit`,
    depotRepAssignments: '/depots/depot-rep-assignments',
  },
  transfers: {
    index: '/transfers',
    create: '/transfers/create',
    show: (id: number | string) => `/transfers/${id}`,
  },
  inventory: {
    products: '/inventory/products',
    productCreate: '/inventory/products/create',
    productShow: (id: string | number) => `/inventory/products/${id}`,
    productEdit: (id: string | number) => `/inventory/products/${id}/edit`,
    systemSetup: '/inventory/system-setup',
    categories: '/inventory/categories',
    taxes: '/inventory/taxes',
    units: '/inventory/units',
    stock: '/inventory/stock',
    reorderLevels: '/inventory/reorder-levels',
  },
  sales: {
    invoices: '/sales/invoices',
    undistributed: '/sales/undistributed',
    distributions: '/sales/distributions',
    deliveredDistributions: '/sales/distributions/delivered',
    pendingDelivery: '/sales/distributions/pending-delivery',
    deliveryConfirmations: '/sales/delivery-confirmations',
    productDeliverySchedule: '/sales/product-delivery-schedule',
    orders: '/sales/orders',
    orderCreate: '/sales/orders/create',
    orderShow: (id: number | string) => `/sales/orders/${id}`,
    orderEdit: (id: number | string) => `/sales/orders/${id}/edit`,
    /** @deprecated Use orders — kept for gradual migration */
    proposals: '/sales/orders',
    proposalCreate: '/sales/orders/create',
    proposalShow: (id: number | string) => `/sales/orders/${id}`,
    proposalEdit: (id: number | string) => `/sales/orders/${id}/edit`,
    returns: '/sales/returns',
    returnCreate: '/sales/returns/create',
    returnShow: (id: number | string) => `/sales/returns/${id}`,
    returnEdit: (id: number | string) => `/sales/returns/${id}/edit`,
    systemSetup: '/sales/system-setup',
    systemSetupPaymentTerms: '/sales/system-setup/payment-terms',
    systemSetupCustomerCategories: '/sales/system-setup/customer-categories',
    systemSetupPaymentReminders: '/sales/system-setup/payment-reminders',
    systemSetupLineItems: '/sales/system-setup/line-items',
  },
  purchase: {
    invoices: '/purchase/invoices',
    bridgings: '/purchase/bridgings',
    unbridged: '/purchase/unbridged',
    supplierBalances: '/account/reports/supplier-balance',
    receivingSchedules: '/distribution/receiving-schedules',
    returns: '/purchase/returns',
    returnCreate: '/purchase/returns/create',
    returnShow: (id: number | string) => `/purchase/returns/${id}`,
    returnEdit: (id: number | string) => `/purchase/returns/${id}/edit`,
  },
  procurement: {
    systemSetup: '/procurement/system-setup',
    systemSetupPaymentTerms: '/procurement/system-setup/payment-terms',
    systemSetupSupplierCategories: '/procurement/system-setup/supplier-categories',
    systemSetupLineItems: '/procurement/system-setup/line-items',
    systemSetupPaymentReminders: '/procurement/system-setup/payment-reminders',
  },
  fleet: {
    trucks: '/fleet/trucks',
    truckCreate: '/fleet/trucks/create',
    truckEdit: (id: string | number) => `/fleet/trucks/${id}/edit`,
    truckShow: (id: string | number) => `/fleet/trucks/${id}`,
    drivers: '/fleet/drivers',
    driverCreate: '/fleet/drivers/create',
    driverEdit: (id: string | number) => `/fleet/drivers/${id}/edit`,
    driverShow: (id: string | number) => `/fleet/drivers/${id}`,
    driverAssignments: '/fleet/driver-assignments',
    truckProviders: '/fleet/truck-providers',
    truckProviderCreate: '/fleet/truck-providers/create',
    truckProviderEdit: (id: string | number) => `/fleet/truck-providers/${id}/edit`,
    truckProviderShow: (id: string | number) => `/fleet/truck-providers/${id}`,
    maintenanceProviders: '/fleet/maintenance-providers',
    maintenanceProviderCreate: '/fleet/maintenance-providers/create',
    maintenanceProviderEdit: (id: string | number) => `/fleet/maintenance-providers/${id}/edit`,
    maintenanceProviderShow: (id: string | number) => `/fleet/maintenance-providers/${id}`,
    truckMaintenances: '/fleet/truck-maintenances',
    truckMaintenanceCreate: '/fleet/truck-maintenances/create',
    truckMaintenanceEdit: (id: string | number) => `/fleet/truck-maintenances/${id}/edit`,
    truckMaintenanceShow: (id: string | number) => `/fleet/truck-maintenances/${id}`,
    truckLoadingDispatchSchedule: '/fleet/truck-loading-dispatch-schedule',
    truckLoadingArrivalSchedule: '/fleet/truck-loading-arrival-schedule',
    truckTrips: '/fleet/truck-trips',
    truckFuelLogs: '/fleet/truck-fuel-logs',
    truckMovements: '/fleet/truck-movements',
    fuelTickets: '/fleet/fuel-tickets',
    truckTracker: '/fleet/truck-tracker',
    truckProviderPayments: '/fleet/truck-provider-payments',
    truckDrivers: '/fleet/truck-drivers',
    truckDriverCreate: '/fleet/truck-drivers/create',
    systemSetup: '/fleet/system-setup',
    systemSetupTruckProviderTypes: '/fleet/system-setup/truck-provider-types',
    systemSetupTruckFuelTypes: '/fleet/system-setup/truck-fuel-types',
    systemSetupTruckComplianceTypes: '/fleet/system-setup/truck-compliance-types',
  },
  assetManagement: {
    dashboard: '/asset-management',
    assets: '/asset-management/assets',
    assetCreate: '/asset-management/assets/create',
    assetEdit: (id: string | number) => `/asset-management/assets/${id}/edit`,
    assetShow: (id: string | number) => `/asset-management/assets/${id}`,
    assetByTag: (tag: string) => `/asset-management/assets/tag/${encodeURIComponent(tag)}`,
    locations: '/asset-management/locations',
    categories: '/asset-management/categories',
    maintenancePlans: '/asset-management/maintenance-plans',
    maintenanceOrders: '/asset-management/maintenance-orders',
    inspections: '/asset-management/inspections',
    reports: '/asset-management/reports',
    depreciation: '/asset-management/depreciation',
  },
  bridging: {
    index: '/bridging/truck-loads',
    truckLoadShow: (id: string | number) => `/bridging/truck-loads/${id}`,
  },
  distribution: {
    emptyTrucksInTransit: '/distribution/empty-trucks-in-transit',
    goodsInTransit: '/distribution/goods-in-transit',
    loadingSchedules: '/distribution/loading-schedules',
    loadingScheduleCreate: '/distribution/loading-schedules/create',
    loadingScheduleShow: (id: string | number) => `/distribution/loading-schedules/${id}`,
    loadingScheduleEdit: (id: string | number) => `/distribution/loading-schedules/${id}/edit`,
    transit: '/distribution/transits',
    transitCreate: '/distribution/transits/create',
    transitShow: (id: string | number) => `/distribution/transits/${id}`,
    transitEdit: (id: string | number) => `/distribution/transits/${id}/edit`,
    deliverySchedules: '/distribution/delivery-schedules',
    deliveryScheduleCreate: '/distribution/delivery-schedules/create',
    deliveryScheduleShow: (id: string | number) => `/distribution/delivery-schedules/${id}`,
    deliveryScheduleEdit: (id: string | number) => `/distribution/delivery-schedules/${id}/edit`,
    shortages: '/distribution/shortages',
    shortageCreate: '/distribution/shortages/create',
    shortageShow: (id: string | number) => `/distribution/shortages/${id}`,
    shortageEdit: (id: string | number) => `/distribution/shortages/${id}/edit`,
    overages: '/distribution/overages',
    overageCreate: '/distribution/overages/create',
    overageShow: (id: string | number) => `/distribution/overages/${id}`,
    overageEdit: (id: string | number) => `/distribution/overages/${id}/edit`,
    inventoryMovements: '/distribution/inventory-movements',
    inventoryMovementCreate: '/distribution/inventory-movements/create',
    inventoryMovementShow: (id: string | number) => `/distribution/inventory-movements/${id}`,
    inventoryMovementEdit: (id: string | number) => `/distribution/inventory-movements/${id}/edit`,
    systemSetup: '/distribution/system-setup',
    systemSetupMovementTypes: '/distribution/system-setup/movement-types',
    receivingSchedules: '/distribution/receiving-schedules',
    receivingScheduleCreate: '/distribution/receiving-schedules/create',
    receivingScheduleShow: (id: string | number) => `/distribution/receiving-schedules/${id}`,
    receivingScheduleEdit: (id: string | number) => `/distribution/receiving-schedules/${id}/edit`,
    deliveryConfirmations: '/distribution/delivery-confirmations',
    deliveryConfirmationCreate: '/distribution/delivery-confirmations/create',
    deliveryConfirmationShow: (id: string | number) => `/distribution/delivery-confirmations/${id}`,
    deliveryConfirmationEdit: (id: string | number) => `/distribution/delivery-confirmations/${id}/edit`,
    information: '/distribution/information',
    informationWithTruckLoad: (id: string | number) =>
      `/distribution/information?truck_load_id=${id}`,
  },
  pos: {
    index: '/pos',
    orders: '/pos/orders',
    create: '/pos/create',
    show: (id: string | number) => `/pos/${id}`,
    edit: (id: string | number) => `/pos/${id}/edit`,
    print: (id: string | number) => `/pos/${id}/print`,
    barcode: '/pos/barcode',
    reports: '/pos/reports',
    reportsSales: '/pos/reports/sales',
    reportsProducts: '/pos/reports/products',
    reportsCustomers: '/pos/reports/customers',
  },
  quotation: {
    index: '/quotation/quotations',
    create: '/quotation/quotations/create',
    show: (id: string | number) => `/quotation/quotations/${id}`,
    edit: (id: string | number) => `/quotation/quotations/${id}/edit`,
    print: (id: string | number) => `/quotation/quotations/${id}/print`,
  },
  hrm: {
    index: '/hrm',
    employees: '/hrm/employees',
    employeeCreate: '/hrm/employees/create',
    employeeShow: (id: string | number) => `/hrm/employees/${id}`,
    employeeEdit: (id: string | number) => `/hrm/employees/${id}/edit`,
    depotReps: '/hrm/employees/depot-reps',
    attendances: '/hrm/attendances',
    leaveTypes: '/hrm/leave-types',
    leaveApplications: '/hrm/leave-applications',
    holidays: '/hrm/holidays',
    awards: '/hrm/awards',
    awardTypes: '/hrm/award-types',
    payrolls: '/hrm/payrolls',
    payrollShow: (id: string | number) => `/hrm/payrolls/${id}`,
    promotions: '/hrm/promotions',
    setSalary: '/hrm/set-salary',
    setSalaryShow: (id: string | number) => `/hrm/set-salary/${id}`,
  },
  goal: {
    index: '/goal',
    create: '/goal/create',
    show: (id: string | number) => `/goal/${id}`,
    edit: (id: string | number) => `/goal/${id}/edit`,
  },
  contract: {
    index: '/contract',
    create: '/contract/create',
    show: (id: string | number) => `/contract/${id}`,
    edit: (id: string | number) => `/contract/${id}/edit`,
  },
  training: {
    index: '/training/trainings',
    create: '/training/trainings/create',
    show: (id: string | number) => `/training/trainings/${id}`,
    edit: (id: string | number) => `/training/trainings/${id}/edit`,
    trainers: '/training/trainers',
    trainerCreate: '/training/trainers/create',
    trainerShow: (id: string | number) => `/training/trainers/${id}`,
    trainerEdit: (id: string | number) => `/training/trainers/${id}/edit`,
    trainingTypes: '/training/training-types',
    systemSetup: '/training/system-setup',
  },
  timesheet: {
    index: '/timesheet/timesheets',
    create: '/timesheet/timesheets/create',
    show: (id: string | number) => `/timesheet/timesheets/${id}`,
    edit: (id: string | number) => `/timesheet/timesheets/${id}/edit`,
  },
  performance: {
    indicators: '/performance/indicators',
    indicatorCreate: '/performance/indicators/create',
    indicatorShow: (id: string | number) => `/performance/indicators/${id}`,
    indicatorEdit: (id: string | number) => `/performance/indicators/${id}/edit`,
    employeeGoals: '/performance/employee-goals',
    employeeGoalCreate: '/performance/employee-goals/create',
    employeeGoalShow: (id: string | number) => `/performance/employee-goals/${id}`,
    employeeGoalEdit: (id: string | number) => `/performance/employee-goals/${id}/edit`,
    reviewCycles: '/performance/review-cycles',
    reviewCycleCreate: '/performance/review-cycles/create',
    reviewCycleShow: (id: string | number) => `/performance/review-cycles/${id}`,
    reviewCycleEdit: (id: string | number) => `/performance/review-cycles/${id}/edit`,
    employeeReviews: '/performance/employee-reviews',
    employeeReviewCreate: '/performance/employee-reviews/create',
    employeeReviewShow: (id: string | number) => `/performance/employee-reviews/${id}`,
    employeeReviewConduct: (id: string | number) => `/performance/employee-reviews/${id}/conduct`,
    employeeReviewEdit: (id: string | number) => `/performance/employee-reviews/${id}/edit`,
    systemSetup: '/performance/system-setup',
  },
  lead: {
    leads: '/lead/leads',
    leadCreate: '/lead/leads/create',
    leadShow: (id: string | number) => `/lead/leads/${id}`,
    leadEdit: (id: string | number) => `/lead/leads/${id}/edit`,
    deals: '/lead/deals',
    dealCreate: '/lead/deals/create',
    dealShow: (id: string | number) => `/lead/deals/${id}`,
    dealEdit: (id: string | number) => `/lead/deals/${id}/edit`,
    pipelines: '/lead/pipelines',
  },
  vendorManagement: {
    vendors: '/vendor-management/vendors',
    vendorCreate: '/vendor-management/vendors/create',
    vendorShow: (id: string | number) => `/vendor-management/vendors/${id}`,
    vendorEdit: (id: string | number) => `/vendor-management/vendors/${id}/edit`,
    tenders: '/vendor-management/tenders',
    tenderCreate: '/vendor-management/tenders/create',
    tenderShow: (id: string | number) => `/vendor-management/tenders/${id}`,
    tenderEdit: (id: string | number) => `/vendor-management/tenders/${id}/edit`,
    /** @deprecated use systemSetupPipelineStages */
    stageTemplates: '/vendor-management/system-setup/pipeline-stages',
    systemSetup: '/vendor-management/system-setup',
    systemSetupPipelineStages: '/vendor-management/system-setup/pipeline-stages',
  },
  recruitment: {
    jobPostings: '/recruitment/job-postings',
    jobPostingCreate: '/recruitment/job-postings/create',
    jobPostingShow: (id: string | number) => `/recruitment/job-postings/${id}`,
    jobPostingEdit: (id: string | number) => `/recruitment/job-postings/${id}/edit`,
    candidates: '/recruitment/candidates',
    candidateCreate: '/recruitment/candidates/create',
    candidateShow: (id: string | number) => `/recruitment/candidates/${id}`,
    candidateEdit: (id: string | number) => `/recruitment/candidates/${id}/edit`,
    jobLocations: '/recruitment/job-locations',
    customQuestions: '/recruitment/custom-questions',
    interviewRounds: '/recruitment/interview-rounds',
    interviews: '/recruitment/interviews',
    interviewCreate: '/recruitment/interviews/create',
    interviewShow: (id: string | number) => `/recruitment/interviews/${id}`,
    interviewEdit: (id: string | number) => `/recruitment/interviews/${id}/edit`,
    interviewFeedbacks: '/recruitment/interview-feedbacks',
    candidateAssessments: '/recruitment/candidate-assessments',
    offers: '/recruitment/offers',
    offerCreate: '/recruitment/offers/create',
    offerShow: (id: string | number) => `/recruitment/offers/${id}`,
    offerEdit: (id: string | number) => `/recruitment/offers/${id}/edit`,
    checklistItems: '/recruitment/checklist-items',
    candidateOnboardings: '/recruitment/candidate-onboardings',
    systemSetup: '/recruitment/system-setup',
  },
  support: {
    tickets: '/support/tickets',
    ticketCreate: '/support/tickets/create',
    ticketShow: (id: string | number) => `/support/tickets/${id}`,
    knowledgeBase: '/support/knowledge-base',
    knowledgeBaseCreate: '/support/knowledge-base/create',
    knowledgeBaseShow: (id: string | number) => `/support/knowledge-base/${id}`,
    knowledgeBaseEdit: (id: string | number) => `/support/knowledge-base/${id}/edit`,
    faqs: '/support/faqs',
    faqCreate: '/support/faqs/create',
    faqShow: (id: string | number) => `/support/faqs/${id}`,
    faqEdit: (id: string | number) => `/support/faqs/${id}/edit`,
    contacts: '/support/contacts',
    portalSettings: '/support/portal-settings',
    systemSetup: '/support-ticket/system-setup',
    ticketCategories: '/support-ticket/categories',
    supportCategories: '/support-ticket/support-categories',
    knowledgeCategories: '/support-ticket/knowledge-categories',
    customPages: '/support-ticket/custom-pages',
    titleSections: '/support-ticket/title-sections',
    ctaSections: '/support-ticket/cta-sections',
    quickLinks: '/support-ticket/quick-links',
    contactInformation: '/support-ticket/contact-information',
  },
  account: {
    index: '/account',
    customers: '/account/customers',
    customerLimitsBalances: '/account/customers/limits-balances',
    customerCreate: '/account/customers/create',
    customerShow: (id: string | number) => `/account/customers/${id}`,
    customerEdit: (id: string | number) => `/account/customers/${id}/edit`,
    creditBalance: '/account/credit-balance',
    creditBalancePrint: '/account/credit-balance/print',
    accountReport: (key: string) => `/account/reports/${key}`,
    accountReportPrint: (key: string) => `/account/reports/${key}/print`,
    suppliers: '/account/suppliers',
    supplierLimitsBalances: '/account/suppliers/limits-balances',
    supplierCreate: '/account/suppliers/create',
    supplierShow: (id: string | number) => `/account/suppliers/${id}`,
    supplierEdit: (id: string | number) => `/account/suppliers/${id}/edit`,
    journalEntries: '/account/journal-entries',
    journalEntryCreate: '/account/journal-entries/create',
    journalEntryShow: (id: string | number) => `/account/journal-entries/${id}`,
    reports: '/account/reports',
    customerPayments: {
      index: '/account/customer-payments',
      create: '/account/customer-payments/create',
      show: (id: string | number) => `/account/customer-payments/${id}`,
    },
    supplierPayments: {
      index: '/account/supplier-payments',
      create: '/account/supplier-payments/create',
      show: (id: string | number) => `/account/supplier-payments/${id}`,
    },
    creditNotes: {
      index: '/account/credit-notes',
      show: (id: string | number) => `/account/credit-notes/${id}`,
    },
    debitNotes: {
      index: '/account/debit-notes',
      show: (id: string | number) => `/account/debit-notes/${id}`,
    },
    chartOfAccounts: '/account/chart-of-accounts',
  },
  taskly: {
    projects: '/taskly/projects',
    projectCreate: '/taskly/projects/create',
    projectEdit: (id: string | number) => `/taskly/projects/${id}/edit`,
    projectShow: (id: string | number) => `/taskly/projects/${id}`,
    projectTasksKanban: (id: string | number) => `/taskly/projects/${id}/tasks/kanban`,
    projectBugsKanban: (id: string | number) => `/taskly/projects/${id}/bugs/kanban`,
  },
  reports: {
    analytics: '/reports',
    operational: (reportKey: string) => `/reports/operational/${reportKey}`,
  },
  portal: {
    dashboard: '/portal',
    invoices: '/portal/invoices',
    invoiceShow: (id: string | number) => `/portal/invoices/${id}`,
    distributionReport: '/portal/distribution-report',
  },
  doubleEntry: {
    ledgerSummary: '/double-entry/ledger-summary',
    ledgerSummaryPrint: '/double-entry/ledger-summary/print',
    trialBalance: '/double-entry/trial-balance',
    trialBalancePrint: '/double-entry/trial-balance/print',
    balanceSheets: '/double-entry/balance-sheets',
    balanceSheetComparisons: '/double-entry/balance-sheets/comparisons',
    balanceSheetShow: (id: number | string) => `/double-entry/balance-sheets/${id}`,
    balanceSheetPrint: (id: number | string) => `/double-entry/balance-sheets/${id}/print`,
    balanceSheetComparisonShow: (id: number | string) =>
      `/double-entry/balance-sheets/comparisons/${id}`,
    balanceSheetComparisonPrint: (id: number | string) =>
      `/double-entry/balance-sheets/comparisons/${id}/print`,
    profitLoss: '/double-entry/profit-loss',
    profitLossPrint: '/double-entry/profit-loss/print',
    reports: '/double-entry/reports',
    otherReport: (key: string) => `/double-entry/reports/${key}`,
    otherReportPrint: (key: string) => `/double-entry/reports/${key}/print`,
  },
  budgetPlanner: {
    periods: '/budget-planner/budget-periods',
    periodCreate: '/budget-planner/budget-periods/create',
    periodEdit: (id: string | number) => `/budget-planner/budget-periods/${id}/edit`,
    budgets: '/budget-planner/budgets',
    budgetCreate: '/budget-planner/budgets/create',
    budgetShow: (id: string | number) => `/budget-planner/budgets/${id}`,
    budgetEdit: (id: string | number) => `/budget-planner/budgets/${id}/edit`,
  },
  plans: '/plans',
  planCreate: '/plans/create',
  planShow: (id: string | number) => `/plans/${id}`,
  planEdit: (id: string | number) => `/plans/${id}/edit`,
  planSubscribe: (id: string | number) => `/plans/${id}/subscribe`,
  subscription: '/subscription',
  billing: '/billing',
  marketplaceSettings: '/landing-page/marketplace/settings',
  integrationsHub: '/settings/integrations',
  helpdesk: '/helpdesk/tickets',
  helpdeskTicketCreate: '/helpdesk/tickets/create',
  helpdeskTicketShow: (id: string | number) => `/helpdesk/tickets/${id}`,
  helpdeskCategories: '/helpdesk/categories',
  helpdeskCategoryCreate: '/helpdesk/categories/create',
  helpdeskCategoryShow: (id: string | number) => `/helpdesk/categories/${id}`,
  helpdeskCategoryEdit: (id: string | number) => `/helpdesk/categories/${id}/edit`,
  messenger: '/messenger',
  landingPage: '/landing-page',
  newsletterSubscribers: '/landing-page/newsletter-subscribers',
  landingPagePages: '/landing-page/pages',
  landingPagePageCreate: '/landing-page/pages/create',
  landingPagePageShow: (id: string | number) => `/landing-page/pages/${id}`,
  landingPagePageEdit: (id: string | number) => `/landing-page/pages/${id}/edit`,
  formBuilderForms: '/form-builder/forms',
  formBuilder: (id: string | number) => `/form-builder/forms/${id}`,
  coupons: '/coupons',
  couponCreate: '/coupons/create',
  couponShow: (id: string | number) => `/coupons/${id}`,
  couponEdit: (id: string | number) => `/coupons/${id}/edit`,
  orders: '/orders',
  orderCreate: '/orders/create',
  orderShow: (id: string | number) => `/orders/${id}`,
  modules: '/modules',
  addOns: '/add-ons',
  bankTransfer: '/bank-transfer',
  integration: (provider: string) => `/settings/integrations/${provider}`,
} as const
