import { paths } from '@/lib/paths'

const explicit: Record<string, string> = {
  dashboard: paths.dashboard,
  'depots.index': paths.depots.index,
  'depots.create': paths.depots.create,
  'depots.depot-rep-assignments': paths.depots.depotRepAssignments,
  'transfers.index': paths.transfers.index,
  'sales-invoices.index': paths.sales.invoices,
  'sales-invoices.destroy': paths.sales.invoices,
  'sales.undistributed.index': paths.sales.undistributed,
  'sales.distributions.index': paths.sales.distributions,
  'sales.delivered-distributions.index': paths.sales.deliveredDistributions,
  'sales.pending-delivery.index': paths.sales.pendingDelivery,
  'sales.delivery-confirmations.index': paths.sales.deliveryConfirmations,
  'sales.product-delivery-schedule.index': paths.sales.productDeliverySchedule,
  'sales-orders.index': paths.sales.proposals,
  'sales-returns.index': paths.sales.returns,
  'purchase-invoices.index': paths.purchase.invoices,
  'purchase-invoices.destroy': paths.purchase.invoices,
  'purchase.unbridged.index': paths.purchase.unbridged,
  'purchase.bridgings.index': paths.purchase.bridgings,
  'purchase.receiving-schedules.index': paths.purchase.receivingSchedules,
  'bridging.truck-loads.index': paths.bridging.index,
  'distribution.empty-trucks-in-transit.index': paths.distribution.emptyTrucksInTransit,
  'distribution.goods-in-transit.index': paths.distribution.goodsInTransit,
  'account.customers.limits-balances': paths.account.customerLimitsBalances,
  'account.suppliers.limits-balances': paths.account.supplierLimitsBalances,
  'purchase-returns.index': paths.purchase.returns,
  'product-service.items.index': paths.inventory.products,
  'product-service.items.destroy': '/product-service/items',
  'product-service.stock.index': paths.inventory.stock,
  'product-service.stock.store': paths.inventory.stock,
  'product-service.item-categories.index': paths.inventory.categories,
  'inventory.system-setup.index': paths.inventory.systemSetup,
  'hrm.system-setup.index': '/hrm/system-setup',
  'account.system-setup.index': '/account/system-setup',
  'account.revenue-categories.index': '/account/revenue-categories',
  'account.expense-categories.index': '/account/expense-categories',
  'project.system-setup.index': '/project/system-setup',
  'performance.system-setup.index': '/performance/system-setup',
  'recruitment.system-setup.index': '/recruitment/system-setup',
  'support-ticket.system-setup.index': '/support-ticket/system-setup',
  'fleet.trucks.index': paths.fleet.trucks,
  'fleet.trucks.destroy': '/fleet/trucks',
  'fleet.drivers.index': '/fleet/drivers',
  'fleet.truck-providers.index': '/fleet/truck-providers',
  'fleet.truck-providers.destroy': '/fleet/truck-providers',
  'fleet.truck-maintenances.index': '/fleet/truck-maintenances',
  'fleet.truck-maintenances.destroy': '/fleet/truck-maintenances',
  'fleet.maintenance-providers.index': '/fleet/maintenance-providers',
  'fleet.maintenance-providers.destroy': '/fleet/maintenance-providers',
  'hrm.employees.index': paths.hrm.employees,
  'hrm.employees.destroy': '/hrm/employees',
  'hrm.employees.depot-reps': paths.hrm.depotReps,
  'depot-rep-assignments.destroy': '/depot-rep-assignments',
  'lead.leads.index': paths.lead.leads,
  'lead.deals.index': paths.lead.deals,
  'lead.pipelines.index': '/lead/pipelines',
  'support-tickets.index': paths.support.tickets,
  'dashboard.support-tickets': paths.dashboards.support,
  'recruitment.job-postings.index': paths.recruitment.jobPostings,
  'project.index': paths.taskly.projects,
  'taskly.projects.destroy': '/taskly/projects',
  'formbuilder.forms.index': '/form-builder/forms',
  'account.index': paths.account.index,
  'account.customers.index': paths.account.customers,
  'account.customers.create': paths.account.customerCreate,
  'account.customers.destroy': paths.account.customers,
  'account.suppliers.index': paths.account.suppliers,
  'account.suppliers.create': paths.account.supplierCreate,
  'account.suppliers.destroy': paths.account.suppliers,
  'account.journal-entries.index': paths.account.journalEntries,
  'account.customer-payments.index': paths.account.customerPayments.index,
  'account.supplier-payments.index': '/account/supplier-payments',
  'account.chart-of-accounts.index': '/account/chart-of-accounts',
  'account.reports.index': '/account/reports',
  'account.reports.supplier-balance': paths.purchase.supplierBalances,
  'double-entry.reports.index': '/double-entry/reports',
  'reports.analytics.index': '/reports',
  'reports.operational.bridging': paths.reports.operational('bridging'),
  login: paths.login,
  logout: paths.login,
  'profile.edit': paths.profile,
  'settings.index': paths.settings,
  'users.index': paths.users.index,
  'users.destroy': '/users',
  'roles.index': paths.roles.index,
  'roles.destroy': '/roles',
  'media-library': paths.media,
  'plans.index': paths.plans,
  'helpdesk-tickets.index': paths.helpdesk,
  'messenger.index': paths.messenger,
  'email-templates.index': paths.emailTemplates,
  'landing-page.index': paths.landingPage,
  'marketplace.settings': paths.marketplaceSettings,
  'landing-page.pages.index': paths.landingPagePages,
  'newsletter-subscribers.index': paths.newsletterSubscribers,
  'hrm.branches.index': '/hrm/branches',
  'hrm.departments.index': '/hrm/departments',
  'hrm.attendances.index': '/hrm/attendances',
  'hrm.shifts.index': '/hrm/shifts',
  'hrm.leave-types.index': '/hrm/leave-types',
  'hrm.leave-applications.index': '/hrm/leave-applications',
  'hrm.leave-balance.index': '/hrm/leave-balance',
  'hrm.set-salary.index': '/hrm/set-salary',
  'hrm.set-salary.show': '/hrm/set-salary/:id',
  'hrm.payrolls.index': '/hrm/payrolls',
  'hrm.holidays.index': '/hrm/holidays',
  'hrm.awards.index': '/hrm/awards',
  'account.bank-accounts.index': '/account/bank-accounts',
  'account.revenues.index': '/account/revenues',
  'account.expenses.index': '/account/expenses',
  'double-entry.ledger-summary.index': paths.doubleEntry.ledgerSummary,
  'double-entry.trial-balance.index': paths.doubleEntry.trialBalance,
  'double-entry.balance-sheets.index': paths.doubleEntry.balanceSheets,
  'double-entry.profit-loss.index': paths.doubleEntry.profitLoss,
  'budget-planner.budgets.index': paths.budgetPlanner.budgets,
  'hrm.index': paths.hrm.index,
  'dashboard.hrm': paths.dashboards.hrm,
  'dashboard.fleet': paths.dashboards.fleet,
  'dashboard.depot': paths.dashboards.depot,
  'dashboard.inventory': paths.dashboards.inventory,
  'dashboard.project': paths.dashboards.project,
  'dashboard.distribution': paths.dashboards.distribution,
  'account.credit-notes.index': paths.account.creditNotes.index,
  'account.debit-notes.index': paths.account.debitNotes.index,
  'account.bank-transactions.index': '/account/bank-transactions',
  'account.bank-transfers.index': '/account/bank-transfers',
  'account.account-types.index': '/account/account-types',
  'project.report.index': '/project/report',
  'project.report.show': '/project/report',
  'project.task-stages.index': '/project/task-stages',
  'distribution.loading-schedules.index': '/distribution/loading-schedules',
  'distribution.receiving-schedules.index': paths.distribution.receivingSchedules,
  'distribution.delivery-confirmations.index': paths.distribution.deliveryConfirmations,
  'distribution.information.index': paths.distribution.information,
  'distribution.transit.index': '/distribution/transits',
  'distribution.delivery-schedules.index': '/distribution/delivery-schedules',
  'distribution.shortages.index': '/distribution/shortages',
  'distribution.overages.index': '/distribution/overages',
  'distribution.inventory-movements.index': paths.distribution.inventoryMovements,
  'distribution.system-setup.index': '/distribution/system-setup',
  'inventory.reorder-levels.index': '/inventory/reorder-levels',
  'fleet.driver-assignments.index': '/fleet/driver-assignments',
  'fleet.truck-assignments.destroy': '/fleet/truck-assignments',
  'fleet.truck-trips.destroy': '/fleet/truck-trips',
  'fleet.truck-fuel-logs.destroy': '/fleet/truck-fuel-logs',
  'fleet.truck-movements.destroy': '/fleet/truck-movements',
  'fleet.fuel-tickets.destroy': '/fleet/fuel-tickets',
  'fleet.truck-provider-payments.destroy': '/fleet/truck-provider-payments',
  'fleet.truck-trips.index': paths.fleet.truckTrips,
  'fleet.truck-loading-dispatch-schedule.index': paths.fleet.truckLoadingDispatchSchedule,
  'fleet.truck-loading-arrival-schedule.index': paths.fleet.truckLoadingArrivalSchedule,
  'fleet.truck-fuel-logs.index': paths.fleet.truckFuelLogs,
  'fleet.truck-movements.index': paths.fleet.truckMovements,
  'fleet.fuel-tickets.index': paths.fleet.fuelTickets,
  'fleet.truck-tracker.index': paths.fleet.truckTracker,
  'fleet.truck-locations.destroy': '/fleet/truck-locations',
  'fleet.truck-provider-payments.index': paths.fleet.truckProviderPayments,
  'fleet.system-setup.index': paths.fleet.systemSetup,
  'procurement.system-setup.index': paths.procurement.systemSetup,
  'sales.system-setup.index': paths.sales.systemSetup,
  'sales.credit-balance.index': '/account/credit-balance',
  'pos.index': paths.pos.index,
  'pos.orders': paths.pos.orders,
  'pos.create': paths.pos.create,
  'pos.barcode': paths.pos.barcode,
  'pos.reports.sales': paths.pos.reportsSales,
  'pos.reports.products': paths.pos.reportsProducts,
  'pos.reports.customers': paths.pos.reportsCustomers,
  'calendar.index': '/calendar',
  'bank-transfer.index': paths.bankTransfer,
  'add-ons.index': paths.addOns,
  'orders.index': paths.orders,
  'support-ticket-knowledge.index': '/support-ticket/knowledge',
  'support-ticket-faq.index': '/support-ticket/faq',
  'support-ticket-contact.index': '/support-ticket/contact',
  'ticket-category.index': '/support-ticket/categories',
  'performance.indicator-categories.index': '/performance/indicator-categories',
  'performance.indicators.index': '/performance/indicators',
  'performance.employee-goals.index': '/performance/employee-goals',
  'performance.review-cycles.index': '/performance/review-cycles',
  'performance.employee-reviews.index': '/performance/employee-reviews',
  'recruitment.job-categories.index': '/recruitment/job-categories',
  'recruitment.job-types.index': '/recruitment/job-types',
  'recruitment.candidates.index': paths.recruitment.candidates,
  'vendor-management.vendors.index': paths.vendorManagement.vendors,
  'vendor-management.tenders.index': paths.vendorManagement.tenders,
  'vendor-management.stage-templates.index': paths.vendorManagement.systemSetupPipelineStages,
  'vendor-management.system-setup.index': paths.vendorManagement.systemSetup,
}

function routeNameToPath(name: string): string {
  const segments = name.split('.')
  if (segments[segments.length - 1] === 'index') {
    segments.pop()
  }
  return `/${segments.join('/')}`
}

function withRouteParams(base: string, params?: Record<string, string | number>): string {
  if (params != null && Object.prototype.hasOwnProperty.call(params, 'id')) {
    return `${base}/${params.id}`
  }
  return base
}

/** Ziggy-compatible route() for ported legacy menus. */
export function route(name: string, params?: Record<string, string | number>): string {
  if (explicit[name]) {
    return withRouteParams(explicit[name], params)
  }
  return withRouteParams(routeNameToPath(name), params)
}
