import type { LucideIcon } from 'lucide-react'
import {
  Bell,
  CalendarRange,
  CircleHelp,
  ClipboardPenLine,
  Gem,
  ImageIcon,
  Kanban,
  LayoutDashboard,
  Mail,
  MessageSquareText,
  Package,
  PackageSearch,
  PieChart,
  ScanBarcode,
  Settings2,
  Share2,
  ShieldCheck,
  ShoppingBasket,
  Store,
  TicketCheck,
  Truck,
  UsersRound,
  Wallet,
  Warehouse,
} from 'lucide-react'

/** Permission-keyed Lucide icons when a menu row has no explicit icon. */
export const MEGA_MENU_TOP_ICONS_BY_PERMISSION: Record<string, LucideIcon> = {
  'manage-dashboard': LayoutDashboard,
  'manage-product-service-item': PackageSearch,
  'manage-depots': Warehouse,
  'manage-distribution': Share2,
  'manage-fleet': Truck,
  'manage-purchase-invoices': ShoppingBasket,
  'manage-customers': Store,
  'manage-project': Kanban,
  'manage-account': Wallet,
  'manage-double-entry': PieChart,
  'manage-users': ShieldCheck,
  'manage-hrm': UsersRound,
  'manage-pos': ScanBarcode,
  'manage-formbuilder': ClipboardPenLine,
  'manage-support-tickets': TicketCheck,
  'manage-calendar': CalendarRange,
  'manage-media': ImageIcon,
  'manage-messenger': MessageSquareText,
  'manage-helpdesk-tickets': CircleHelp,
  'manage-plans': Gem,
  'manage-email-templates': Mail,
  'manage-notification-templates': Bell,
  'manage-add-on': Package,
  'manage-settings': Settings2,
}
