import {
  Activity,
  AlertTriangle,
  ArrowLeftRight,
  ArrowRightLeft,
  BarChart3,
  Barcode,
  BookOpen,
  BookText,
  Boxes,
  Building2,
  Calendar,
  CalendarClock,
  CalendarDays,
  CheckCircle,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  FileBarChart,
  FileMinus,
  FilePlus,
  FileSpreadsheet,
  FileText,
  FolderKanban,
  FormInput,
  Fuel,
  Gauge,
  GraduationCap,
  Headphones,
  HelpCircle,
  Image,
  Info,
  Landmark,
  Layers,
  LayoutGrid,
  LineChart,
  Link2,
  List,
  LogOut,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquareWarning,
  Move,
  Package,
  PackageCheck,
  PackageX,
  Plus,
  Receipt,
  Replace,
  Route,
  Scale,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Store,
  Ticket,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Undo2,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  UserX,
  Wallet,
  Warehouse,
  Wrench,
} from 'lucide-react'
import type { NavItem } from '@/types'
import { route } from '@/lib/route'

export const getCompanyMenu = (t: (key: string) => string): NavItem[] => [
  {
    title: t('Dashboard'),
    icon: LayoutGrid,
    permission: 'manage-dashboard',
    name: 'dashboard',
    order: 10,
    children: [
      {
        title: t('Overview'),
        href: route('dashboard'),
        icon: LayoutGrid,
        permission: 'manage-dashboard',
        order: 10,
        megaMenuGroup: t('Overview'),
        matchExact: true,
      },
      {
        title: t('Account Dashboard'),
        href: route('account.index'),
        icon: DollarSign,
        permission: 'manage-account-dashboard',
        order: 11,
        megaMenuGroup: t('Overview'),
        matchExact: true,
      },
      {
        title: t('HRM Dashboard'),
        href: route('hrm.index'),
        icon: UserCog,
        permission: 'manage-hrm-dashboard',
        modules: ['Hrm'],
        order: 12,
        megaMenuGroup: t('Integrations'),
        matchExact: true,
      },
      {
        title: t('Fleet Dashboard'),
        href: route('dashboard.fleet'),
        icon: Truck,
        permission: 'manage-fleet-dashboard',
        order: 13,
        megaMenuGroup: t('Overview'),
      },
      {
        title: t('Depot Dashboard'),
        href: route('dashboard.depot'),
        icon: Warehouse,
        permission: 'manage-depot-dashboard',
        order: 14,
        megaMenuGroup: t('Integrations'),
      },
      {
        title: t('Inventory Dashboard'),
        href: route('dashboard.inventory'),
        icon: Layers,
        permission: 'manage-product-service-item',
        order: 15,
        megaMenuGroup: t('Integrations'),
      },
      {
        title: t('Project Dashboard'),
        href: route('dashboard.project'),
        icon: FolderKanban,
        permission: 'manage-project-dashboard',
        order: 16,
        modules: ['Taskly'],
        megaMenuGroup: t('Integrations'),
      },
      {
        title: t('Distribution Dashboard'),
        href: route('dashboard.distribution'),
        icon: Route,
        permission: 'manage-distribution-dashboard',
        order: 17,
        megaMenuGroup: t('Integrations'),
      },
      {
        title: t('POS Dashboard'),
        href: route('pos.index'),
        icon: Store,
        permission: 'manage-pos-dashboard',
        parent: 'dashboard',
        order: 17,
        megaMenuGroup: t('Integrations'),
        matchExact: true,
      },
      {
        title: t('Support Dashboard'),
        href: route('dashboard.support-tickets'),
        icon: Headphones,
        permission: 'manage-dashboard-support-ticket',
        modules: ['SupportTicket'],
        order: 18,
        megaMenuGroup: t('Integrations'),
      },
    ],
  },
  {
    title: t('Inventory'),
    icon: Layers,
    permission: 'manage-product-service-item',
    modules: ['ProductService'],
    order: 20,
    children: [
      {
        title: t('List of Products'),
        href: route('product-service.items.index'),
        icon: Package,
        permission: 'manage-product-service-item',
      },
      {
        title: t('Product Stock'),
        href: route('product-service.stock.index'),
        icon: Boxes,
        permission: 'manage-stock',
      },
      {
        title: t('Reorder levels'),
        href: route('inventory.reorder-levels.index'),
        icon: Gauge,
        permission: 'manage-product-service-item',
      },
      {
        title: t('System Setup'),
        href: route('inventory.system-setup.index'),
        icon: Settings,
        permission: 'manage-product-service-item',
      },
    ],
  },
  {
    title: t('Depot'),
    icon: Warehouse,
    permission: 'manage-depots',
    order: 70,
    children: [
      {
        title: t('List of Depots'),
        href: route('depots.index'),
        icon: List,
        permission: 'manage-depots',
      },
      {
        title: t('Receiving Schedules'),
        href: route('distribution.receiving-schedules.index'),
        icon: PackageCheck,
        permission: 'manage-depot-schedules',
      },
      {
        title: t('Loading Schedules'),
        href: route('distribution.loading-schedules.index'),
        icon: Upload,
        permission: 'view-loading-schedules',
      },
      {
        title: t('Delivery Schedules'),
        href: route('distribution.delivery-schedules.index'),
        icon: CalendarClock,
        permission: 'view-delivery-schedules',
      },
      {
        title: t('Depot Reps'),
        href: route('hrm.employees.depot-reps'),
        icon: UserCheck,
        permission: 'manage-depot-reps',
      },
      {
        title: t('Depot Rep Assignments'),
        href: route('depots.depot-rep-assignments'),
        icon: UserPlus,
        permission: 'manage-depot-rep-assignments',
      },
    ],
  },
  {
    title: t('Distribution'),
    icon: Replace,
    permission: 'manage-distribution',
    modules: ['Distribution'],
    order: 60,
    children: [
      {
        title: t('Depot Transfers'),
        href: route('transfers.index'),
        icon: ArrowLeftRight,
        permission: 'manage-transfers',
      },
      {
        title: t('Transit Monitoring'),
        href: route('distribution.transit.index'),
        icon: MapPin,
        permission: 'view-transits',
      },
      {
        title: t('Distributed Trucks'),
        href: route('bridging.truck-loads.index'),
        icon: Truck,
        permission: 'manage-bridging',
      },
      {
        title: t('Empty Truck in Transit'),
        href: route('distribution.empty-trucks-in-transit.index'),
        icon: Truck,
        permission: 'manage-bridging',
      },
      {
        title: t('Goods in Transit'),
        href: route('distribution.goods-in-transit.index'),
        icon: Truck,
        permission: 'manage-bridging',
      },
      {
        title: t('Delivery Confirmations'),
        href: route('distribution.delivery-confirmations.index'),
        icon: CheckCircle2,
        permission: 'manage-delivery-schedules',
      },
      {
        title: t('Distribution Information'),
        href: route('distribution.information.index'),
        icon: Info,
        permission: 'view-loading-schedules',
      },
      {
        title: t('Delivery Shortages'),
        href: route('distribution.shortages.index'),
        icon: TrendingDown,
        permission: 'view-shortages',
      },
      {
        title: t('Delivery Overages'),
        href: route('distribution.overages.index'),
        icon: TrendingUp,
        permission: 'view-overages',
      },
      {
        title: t('Inventory Movements'),
        href: route('distribution.inventory-movements.index'),
        icon: Move,
        permission: 'view-inventory-movements',
      },
      {
        title: t('System Setup'),
        href: route('distribution.system-setup.index'),
        icon: Settings,
        permission: 'manage-inventory-movement-types',
      },
    ],
  },
  {
    title: t('Fleet'),
    icon: Truck,
    permission: 'manage-fleet',
    modules: ['Fleet'],
    order: 50,
    children: [
      {
        title: t('List of Trucks'),
        href: route('fleet.trucks.index'),
        icon: Truck,
        permission: 'manage-trucks',
      },
      {
        title: t('Truck Tracker'),
        href: route('fleet.truck-tracker.index'),
        icon: MapPin,
        permission: 'manage-fleet',
      },
      {
        title: t('Truck Providers'),
        href: route('fleet.truck-providers.index'),
        icon: Building2,
        permission: 'manage-truck-providers',
      },
      {
        title: t('List of Drivers'),
        href: route('fleet.drivers.index'),
        icon: User,
        permission: 'manage-drivers',
      },
      {
        title: t('Driver Assignments'),
        href: route('fleet.driver-assignments.index'),
        icon: UserCheck,
        permission: 'manage-truck-assignments',
      },
      {
        title: t('Truck Movements'),
        href: route('fleet.truck-movements.index'),
        icon: Route,
        permission: 'manage-truck-movements',
      },
      {
        title: t('Truck Trips'),
        href: route('fleet.truck-trips.index'),
        icon: Map,
        permission: 'view-truck-trips',
      },
      {
        title: t('Truck Loading Dispatch Schedule'),
        href: route('fleet.truck-loading-dispatch-schedule.index'),
        icon: Upload,
        permission: 'view-loading-schedules',
      },
      {
        title: t('Truck Loading Arrival Schedule'),
        href: route('fleet.truck-loading-arrival-schedule.index'),
        icon: PackageCheck,
        permission: 'manage-depot-schedules',
      },
      {
        title: t('Truck Provider Payments'),
        href: route('fleet.truck-provider-payments.index'),
        icon: Wallet,
        permission: 'manage-truck-provider-payments',
      },
      {
        title: t('Fuel Tickets'),
        href: route('fleet.fuel-tickets.index'),
        icon: Fuel,
        permission: 'manage-fuel-tickets',
      },
      {
        title: t('Fuel Logs'),
        href: route('fleet.truck-fuel-logs.index'),
        icon: ClipboardList,
        permission: 'view-truck-fuel-logs',
      },
      {
        title: t('Truck Maintenances'),
        href: route('fleet.truck-maintenances.index'),
        icon: Wrench,
        permission: 'manage-truck-maintenances',
      },
      {
        title: t('Maintenance Providers'),
        href: route('fleet.maintenance-providers.index'),
        icon: Building2,
        permission: 'manage-maintenance-providers',
      },
      {
        title: t('System Setup'),
        href: route('fleet.system-setup.index'),
        icon: Settings,
        permission: 'manage-truck-provider-types',
      },
    ],
  },
  {
    title: t('Vendor Mgt.'),
    icon: ClipboardList,
    // Parent has no permission gate so fine-grained child perms (view-vm-*) work.
    modules: ['VendorManagement'],
    order: 51,
    children: [
      {
        title: t('Vendors'),
        href: route('vendor-management.vendors.index'),
        icon: Building2,
        permission: 'view-vm-vendors',
      },
      {
        title: t('Tenders'),
        href: route('vendor-management.tenders.index'),
        icon: FileText,
        permission: 'view-vm-tenders',
      },
      {
        title: t('System Setup'),
        href: route('vendor-management.system-setup.index'),
        icon: Settings,
        permission: 'manage-vendor-management',
      },
    ],
  },
  {
    title: t('Assets'),
    icon: Layers,
    permission: 'manage-assets',
    modules: ['AssetManagement'],
    order: 52,
    children: [
      {
        title: t('Dashboard'),
        href: '/asset-management',
        icon: Gauge,
        permission: 'manage-asset-management-dashboard',
      },
      {
        title: t('Assets'),
        href: '/asset-management/assets',
        icon: Package,
        permission: 'view-assets',
      },
      {
        title: t('Locations'),
        href: '/asset-management/locations',
        icon: MapPin,
        permission: 'view-asset-locations',
      },
      {
        title: t('Categories'),
        href: '/asset-management/categories',
        icon: List,
        permission: 'view-asset-categories',
      },
      {
        title: t('Maintenance plans'),
        href: '/asset-management/maintenance-plans',
        icon: CalendarClock,
        permission: 'view-asset-maintenance',
      },
      {
        title: t('Maintenance orders'),
        href: '/asset-management/maintenance-orders',
        icon: Wrench,
        permission: 'view-asset-maintenance',
      },
      {
        title: t('Inspections'),
        href: '/asset-management/inspections',
        icon: ClipboardList,
        permission: 'view-asset-inspections',
      },
      {
        title: t('Reports'),
        href: '/asset-management/reports',
        icon: FileBarChart,
        permission: 'view-asset-reports',
      },
      {
        title: t('Depreciation'),
        href: '/asset-management/depreciation',
        icon: DollarSign,
        permission: 'manage-asset-depreciation',
      },
    ],
  },
  {
    title: t('Procurement'),
    icon: ShoppingCart,
    permission: 'manage-purchase-invoices',
    order: 40,
    children: [
      {
        title: t('List of Suppliers'),
        href: route('account.suppliers.index'),
        icon: Building2,
        permission: 'manage-suppliers',
      },
      {
        title: t('Supplier Limits & Balances'),
        href: route('account.suppliers.limits-balances'),
        icon: Scale,
        permission: 'manage-suppliers',
      },
      {
        title: t('Purchase Invoices'),
        href: route('purchase-invoices.index'),
        icon: ShoppingCart,
        permission: 'manage-purchase-invoices',
      },
      {
        title: t('Purchase Returns'),
        href: route('purchase-returns.index'),
        icon: Undo2,
        permission: 'manage-purchase-return-invoices',
      },
      {
        title: t('List of Bridgings'),
        href: route('purchase.bridgings.index'),
        icon: Link2,
        permission: 'manage-bridging',
      },
      {
        title: t('Unbridged Purchases'),
        href: route('purchase.unbridged.index'),
        icon: PackageX,
        permission: 'manage-purchase-invoices',
      },
      {
        title: t('Supplier Balances'),
        href: route('account.reports.supplier-balance'),
        icon: Scale,
        permission: 'manage-account-reports',
      },
      {
        title: t('Receiving Schedules'),
        href: route('purchase.receiving-schedules.index'),
        icon: PackageCheck,
        permission: 'manage-depot-schedules',
      },
      {
        title: t('Supplier Payments'),
        href: route('account.supplier-payments.index'),
        icon: CreditCard,
        permission: 'manage-supplier-payments',
      },
      {
        title: t('System Setup'),
        href: route('procurement.system-setup.index'),
        icon: Settings,
        permission: 'manage-procurement-payment-terms',
      },
    ],
  },
  {
    title: t('Sales'),
    icon: Users,
    permission: 'manage-customers',
    order: 30,
    children: [
      {
        title: t('List of Customers'),
        href: route('account.customers.index'),
        icon: Users,
        permission: 'manage-customers',
      },
      {
        title: t('Sales Orders'),
        href: route('sales-orders.index'),
        icon: FileText,
        permission: 'manage-sales-orders',
      },
      {
        title: t('Sales Invoices'),
        icon: Receipt,
        href: route('sales-invoices.index'),
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Undistributed Sales'),
        href: route('sales.undistributed.index'),
        icon: Package,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('List of Distributions'),
        href: route('sales.distributions.index'),
        icon: Truck,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Delivered distributions'),
        href: route('sales.delivered-distributions.index'),
        icon: CheckCircle,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Distribution pending delivery'),
        href: route('sales.pending-delivery.index'),
        icon: Clock,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Delivery Confirmations'),
        href: route('sales.delivery-confirmations.index'),
        icon: CheckCircle2,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Product Delivery Schedule'),
        href: route('sales.product-delivery-schedule.index'),
        icon: Calendar,
        permission: 'manage-sales-invoices',
      },
      {
        title: t('Sales Invoice Returns'),
        href: route('sales-returns.index'),
        icon: Undo2,
        permission: 'manage-sales-return-invoices',
      },
      {
        title: t('Customer Payments'),
        href: route('account.customer-payments.index'),
        icon: Wallet,
        permission: 'manage-customer-payments',
      },
      {
        title: t('Customer Limits & Balances'),
        href: route('account.customers.limits-balances'),
        icon: Scale,
        permission: 'manage-customers',
      },
      {
        title: t('Credit Balance'),
        href: route('sales.credit-balance.index'),
        icon: CreditCard,
        permission: 'view-customer-balance',
      },
      {
        title: t('System Setup'),
        href: route('sales.system-setup.index'),
        icon: Settings,
        permission: 'manage-sales-payment-terms',
      },
    ],
  },
  {
    title: t('Projects'),
    icon: FolderKanban,
    permission: 'manage-project',
    name: 'project',
    modules: ['Taskly'],
    order: 120,
    children: [
      {
        title: t('List of Projects'),
        href: route('project.index'),
        icon: FolderKanban,
        permission: 'manage-project',
      },
      {
        title: t('Projects Report'),
        href: route('project.report.index'),
        icon: BarChart3,
        permission: 'manage-project-report',
      },
      {
        title: t('System Setup'),
        href: route('project.system-setup.index'),
        icon: Settings,
        permission: 'manage-task-stages',
      },
    ],
  },
  {
    title: t('Accounting'),
    icon: DollarSign,
    permission: 'manage-account',
    modules: ['Account'],
    order: 80,
    children: [
      {
        title: t('Banking'),
        icon: Landmark,
        permission: 'manage-bank-accounts',
        children: [
          {
            title: t('Bank Accounts'),
            href: route('account.bank-accounts.index'),
            icon: Landmark,
            permission: 'manage-bank-accounts',
          },
          {
            title: t('Bank Transactions'),
            href: route('account.bank-transactions.index'),
            icon: ArrowLeftRight,
            permission: 'manage-bank-transactions',
          },
          {
            title: t('Bank Transfers'),
            href: route('account.bank-transfers.index'),
            icon: Send,
            permission: 'manage-bank-transfers',
          },
          {
            title: t('Chart Of Accounts'),
            href: route('account.chart-of-accounts.index'),
            icon: BookOpen,
            permission: 'manage-chart-of-accounts',
          },
        ],
      },
      {
        title: t('Revenue'),
        href: route('account.revenues.index'),
        icon: TrendingUp,
        permission: 'manage-revenues',
      },
      {
        title: t('Expense'),
        href: route('account.expenses.index'),
        icon: TrendingDown,
        permission: 'manage-expenses',
      },
      {
        title: t('Debit Notes'),
        href: route('account.debit-notes.index'),
        icon: FileMinus,
        permission: 'manage-debit-notes',
      },
      {
        title: t('Credit Notes'),
        href: route('account.credit-notes.index'),
        icon: FilePlus,
        permission: 'manage-credit-notes',
      },
      {
        title: t('Reports'),
        href: route('account.reports.index'),
        icon: BarChart3,
        permission: 'manage-account-reports',
      },
      {
        title: t('System Setup'),
        href: route('account.system-setup.index'),
        icon: Settings,
        permission: 'manage-account-types',
      },
    ],
  },
  {
    title: t('Reports'),
    icon: BookOpen,
    permission: 'manage-double-entry',
    modules: ['DoubleEntry'],
    order: 130,
    children: [
      {
        title: t('All reports'),
        href: route('reports.analytics.index'),
        icon: BookOpen,
        permission: 'manage-double-entry',
      },
      {
        title: t('Operational reports'),
        href: route('reports.operational.bridging'),
        icon: Activity,
        permission: 'view-operational-reports',
      },
      {
        title: t('Ledger Summary'),
        href: route('double-entry.ledger-summary.index'),
        icon: BookText,
        permission: 'manage-ledger-summary',
      },
      {
        title: t('Trial Balance'),
        href: route('double-entry.trial-balance.index'),
        icon: Scale,
        permission: 'manage-trial-balance',
      },
      {
        title: t('Balance Sheets'),
        href: route('double-entry.balance-sheets.index'),
        icon: FileSpreadsheet,
        permission: 'manage-balance-sheets',
      },
      {
        title: t('Profit & Loss'),
        href: route('double-entry.profit-loss.index'),
        icon: LineChart,
        permission: 'manage-profit-loss',
      },
      {
        title: t('Other Reports'),
        href: route('double-entry.reports.index'),
        icon: FileBarChart,
        permission: 'manage-double-entry-reports',
      },
    ],
  },
  {
    title: t('Users & Roles'),
    icon: Users,
    permission: 'manage-users',
    order: 90,
    children: [
      {
        title: t('Roles'),
        href: route('roles.index'),
        icon: Shield,
        permission: 'manage-roles',
      },
      {
        title: t('Users'),
        href: route('users.index'),
        icon: Users,
        permission: 'manage-users',
      },
    ],
  },
  {
    title: t('HRM'),
    icon: UserCog,
    permission: 'manage-hrm',
    modules: ['Hrm'],
    order: 25,
    children: [
      {
        icon: Users,
        title: t('Employees'),
        href: route('hrm.employees.index'),
        permission: 'manage-employees',
      },
      {
        title: t('Payroll & Attendance'),
        icon: Wallet,
        permission: 'manage-hrm',
        children: [
          {
            title: t('Set Salary'),
            href: route('hrm.set-salary.index'),
            icon: DollarSign,
            permission: 'manage-set-salary',
          },
          {
            title: t('Payroll'),
            href: route('hrm.payrolls.index'),
            icon: Receipt,
            permission: 'manage-payrolls',
          },
          {
            title: t('Shifts'),
            href: route('hrm.shifts.index'),
            icon: Calendar,
            permission: 'manage-shifts',
          },
          {
            title: t('Attendances'),
            href: route('hrm.attendances.index'),
            icon: CheckCircle,
            permission: 'manage-attendances',
          },
          {
            title: t('Leave Types'),
            href: route('hrm.leave-types.index'),
            icon: List,
            permission: 'manage-leave-types',
          },
          {
            title: t('Leave Applications'),
            href: route('hrm.leave-applications.index'),
            icon: FileText,
            permission: 'manage-leave-applications',
          },
          {
            title: t('Leave Balance'),
            href: route('hrm.leave-balance.index'),
            icon: Scale,
            permission: 'manage-leave-balance',
          },
          {
            title: t('Holidays'),
            href: route('hrm.holidays.index'),
            icon: Calendar,
            permission: 'manage-holidays',
          },
        ],
      },
      {
        title: t('Talent'),
        icon: GraduationCap,
        permission: 'manage-hrm',
        children: [
          {
            title: t('Performance Indicators'),
            href: route('performance.indicators.index'),
            icon: Gauge,
            permission: 'manage-performance-indicators',
          },
          {
            title: t('Employee Goals'),
            href: route('performance.employee-goals.index'),
            icon: CheckSquare,
            permission: 'manage-employee-goals',
          },
          {
            title: t('Review Cycles'),
            href: route('performance.review-cycles.index'),
            icon: Calendar,
            permission: 'manage-review-cycles',
          },
          {
            title: t('Employee Reviews'),
            href: route('performance.employee-reviews.index'),
            icon: ClipboardList,
            permission: 'manage-employee-reviews',
          },
          {
            title: t('Job Postings'),
            href: route('recruitment.job-postings.index'),
            icon: FileText,
            permission: 'manage-job-postings',
          },
          {
            title: t('Candidates'),
            href: route('recruitment.candidates.index'),
            icon: Users,
            permission: 'manage-candidates',
          },
          {
            title: t('Interviews'),
            href: route('recruitment.interviews.index'),
            icon: CalendarClock,
            permission: 'manage-interviews',
          },
          {
            title: t('Offers'),
            href: route('recruitment.offers.index'),
            icon: Send,
            permission: 'manage-offers',
          },
          {
            title: t('Candidate Onboarding'),
            href: route('recruitment.candidate-onboardings.index'),
            icon: UserCheck,
            permission: 'manage-candidate-onboardings',
          },
          {
            title: t('Training Types'),
            href: route('training.training-types.index'),
            icon: List,
            permission: 'manage-training-types',
          },
          {
            title: t('Trainers'),
            href: route('training.trainers.index'),
            icon: UserCheck,
            permission: 'manage-trainers',
          },
          {
            title: t('Training List'),
            href: route('training.trainings.index'),
            icon: GraduationCap,
            permission: 'manage-trainings',
          },
        ],
      },
      {
        title: t('Employee Relations'),
        icon: Megaphone,
        permission: 'manage-hrm',
        children: [
          {
            title: t('Awards'),
            href: route('hrm.awards.index'),
            icon: Trophy,
            permission: 'manage-awards',
          },
          {
            title: t('Promotions'),
            href: route('hrm.promotions.index'),
            icon: TrendingUp,
            permission: 'manage-promotions',
          },
          {
            title: t('Resignations'),
            href: route('hrm.resignations.index'),
            icon: LogOut,
            permission: 'manage-resignations',
          },
          {
            title: t('Terminations'),
            href: route('hrm.terminations.index'),
            icon: UserX,
            permission: 'manage-terminations',
          },
          {
            title: t('Warnings'),
            href: route('hrm.warnings.index'),
            icon: AlertTriangle,
            permission: 'manage-warnings',
          },
          {
            title: t('Complaints'),
            href: route('hrm.complaints.index'),
            icon: MessageSquareWarning,
            permission: 'manage-complaints',
          },
          {
            title: t('Transfers'),
            href: route('hrm.employee-transfers.index'),
            icon: ArrowRightLeft,
            permission: 'manage-employee-transfers',
          },
          {
            title: t('Documents'),
            href: route('hrm.documents.index'),
            icon: FileText,
            permission: 'manage-hrm-documents',
          },
          {
            title: t('Acknowledgments'),
            href: route('hrm.acknowledgments.index'),
            icon: CheckSquare,
            permission: 'manage-acknowledgments',
          },
          {
            title: t('Announcements'),
            href: route('hrm.announcements.index'),
            icon: Megaphone,
            permission: 'manage-announcements',
          },
          {
            title: t('Events'),
            href: route('hrm.events.index'),
            icon: CalendarDays,
            permission: 'manage-events',
          },
        ],
      },
      {
        title: t('HR Setup'),
        icon: Settings,
        permission: 'manage-hrm',
        children: [
          {
            title: t('Performance Setup'),
            href: route('performance.system-setup.index'),
            icon: Gauge,
            permission: 'manage-performance-system-setup',
          },
          {
            title: t('Recruitment Setup'),
            href: route('recruitment.system-setup.index'),
            icon: UserPlus,
            permission: 'manage-recruitment-system-setup',
          },
          {
            title: t('Job Locations'),
            href: route('recruitment.job-locations.index'),
            icon: MapPin,
            permission: 'manage-job-locations',
          },
          {
            title: t('Custom Questions'),
            href: route('recruitment.custom-questions.index'),
            icon: HelpCircle,
            permission: 'manage-custom-questions',
          },
          {
            title: t('Interview Rounds'),
            href: route('recruitment.interview-rounds.index'),
            icon: List,
            permission: 'manage-interview-rounds',
          },
          {
            title: t('Interview Feedback'),
            href: route('recruitment.interview-feedbacks.index'),
            icon: MessageSquareWarning,
            permission: 'manage-interview-feedbacks',
          },
          {
            title: t('Candidate Assessments'),
            href: route('recruitment.candidate-assessments.index'),
            icon: ClipboardList,
            permission: 'manage-candidate-assessments',
          },
          {
            title: t('Checklist Items'),
            href: route('recruitment.checklist-items.index'),
            icon: CheckSquare,
            permission: 'manage-checklist-items',
          },
          {
            title: t('HRM System Setup'),
            href: route('hrm.system-setup.index'),
            icon: Settings,
            permission: 'manage-hrm',
          },
        ],
      },
    ],
  },
  {
    title: t('POS'),
    icon: Store,
    permission: 'manage-pos',
    order: 110,
    children: [
      {
        title: t('Add POS'),
        href: route('pos.create'),
        icon: Plus,
        permission: 'create-pos',
      },
      {
        title: t('POS Orders'),
        href: route('pos.orders'),
        icon: ShoppingBag,
        permission: 'manage-pos-orders',
      },
      {
        title: t('Print Barcode'),
        href: route('pos.barcode'),
        icon: Barcode,
        permission: 'manage-pos-barcodes',
      },
      {
        title: t('Reports'),
        icon: BarChart3,
        permission: 'manage-pos-reports',
        children: [
          {
            title: t('Sales Report'),
            href: route('pos.reports.sales'),
            icon: TrendingUp,
            permission: 'view-pos-reports',
          },
          {
            title: t('Product Report'),
            href: route('pos.reports.products'),
            icon: Package,
            permission: 'view-pos-reports',
          },
          {
            title: t('Customer Report'),
            href: route('pos.reports.customers'),
            icon: Users,
            permission: 'view-pos-reports',
          },
        ],
      },
    ],
  },
  {
    title: t('Form Builder'),
    icon: FormInput,
    permission: 'manage-formbuilder',
    modules: ['FormBuilder'],
    order: 190,
    href: route('formbuilder.forms.index'),
  },
  {
    title: t('Support Tickets'),
    icon: Headphones,
    permission: 'manage-support-tickets',
    modules: ['SupportTicket'],
    order: 170,
    children: [
      {
        title: t('Tickets'),
        href: route('support-tickets.index'),
        icon: Ticket,
        permission: 'manage-support-tickets',
      },
      {
        title: t('Knowledge Base'),
        href: route('support-ticket-knowledge.index'),
        icon: BookOpen,
        permission: 'manage-knowledge-base',
      },
      {
        title: t('FAQ'),
        href: route('support-ticket-faq.index'),
        icon: HelpCircle,
        permission: 'manage-faq',
      },
      {
        title: t('Contact'),
        href: route('support-ticket-contact.index'),
        icon: Mail,
        permission: 'manage-contact',
      },
      {
        title: t('System Setup'),
        href: route('support-ticket.system-setup.index'),
        icon: Settings,
        permission: 'manage-ticket-categories',
      },
    ],
  },
  {
    title: t('Calendar'),
    href: route('calendar.index'),
    icon: Calendar,
    permission: 'manage-calendar',
    modules: ['Calendar'],
    order: 150,
  },
  {
    title: t('Media Library'),
    href: route('media-library'),
    icon: Image,
    permission: 'manage-media',
    order: 160,
  },
  {
    title: t('Messenger'),
    href: route('messenger.index'),
    icon: MessageCircle,
    permission: 'manage-messenger',
    order: 140,
  },
  {
    title: t('Helpdesk'),
    href: route('helpdesk-tickets.index'),
    icon: Headphones,
    permission: 'manage-helpdesk-tickets',
    order: 180,
  },
  {
    title: t('Subscription'),
    icon: CreditCard,
    permission: 'manage-plans',
    order: 200,
    children: [
      {
        title: t('Setup Subscription Plan'),
        href: route('plans.index'),
        icon: CreditCard,
        permission: 'manage-plans',
      },
      {
        title: t('Bank Transfer Requests'),
        href: route('bank-transfer.index'),
        icon: Landmark,
        permission: 'manage-bank-transfer-requests',
      },
      {
        title: t('Orders'),
        href: route('orders.index'),
        icon: ShoppingBag,
        permission: 'manage-orders',
      },
    ],
  },
  {
    title: t('Settings'),
    href: route('settings.index'),
    icon: Settings,
    permission: 'manage-settings',
    order: 210,
  },
]
